# Generated by Django 3.1.2 on 2020-10-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tweetmodel',
            new_name='model_tweet',
        ),
    ]
